name: Build SUNAT SQLite

on:
  schedule:
    # Todos los días 02:00 AM hora Perú aproximadamente UTC-5, que es 07:00 AM UTC
    # GitHub usa UTC
    - cron: '0 7 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Generar SQLite
        run: |
          python scripts/build_sqlite.py

      - name: Mostrar resultado
        run: |
          ls -lh output/

      # - name: Verificar integridad SQLite
      #   run: |
      #     python - <<'PY'
      #     import sqlite3

      #     conn = sqlite3.connect("output/sunat.sqlite")
      #     r = conn.execute("PRAGMA integrity_check").fetchone()[0]
      #     conn.close()

      #     if r != "ok":
      #         raise Exception(r)

      #     print("SQLite OK")
      #     PY

      - name: Instalar Turso CLI
        run: |
          curl -sSfL https://get.tur.so/install.sh | bash
          echo "$HOME/.turso" >> $GITHUB_PATH

      - name: Verificar Turso
        run: |
          turso --version

      # - name: Login Turso
      #   env:
      #     TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
      #   run: |
      #     turso auth login --token "$TURSO_API_TOKEN"

      - name: Ayuda import
        run: |
          turso db import --help

      - name: Importar y reemplazar Base de Datos en Turso
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
        run: |
          if turso db show sunat &>/dev/null; then
            echo "La base de datos existe. Eliminándola..."
            turso db destroy sunat --yes
          else
            echo "La base de datos no existe."
          fi
          echo "Subiendo archivo desde output/sunat.sqlite al grupo 'test'..."
          turso db import --group test output/sunat.sqlite