name: Build SUNAT SQLite

on:
  schedule:
    # Todos los días 02:00 AM hora Perú aproximadamente UTC-5, que es 07:00 AM UTC
    # GitHub usa UTC
    - cron: '0 7 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Generar SQLite
        run: |
          python scripts/build_sqlite.py

      - name: Mostrar resultado
        run: |
          ls -lh output/

      # - name: Verificar integridad SQLite
      #   run: |
      #     python - <<'PY'
      #     import sqlite3

      #     conn = sqlite3.connect("output/sunat.sqlite")
      #     r = conn.execute("PRAGMA integrity_check").fetchone()[0]
      #     conn.close()

      #     if r != "ok":
      #         raise Exception(r)

      #     print("SQLite OK")
      #     PY

      - name: Instalar Turso CLI
        run: |
          curl -sSfL https://get.tur.so/install.sh | bash
          echo "$HOME/.turso" >> $GITHUB_PATH

      - name: Verificar Turso
        run: |
          turso --version
      - name: Forzar modo WAL y Checkpoint en SQLite
        run: |
          sqlite3 output/sunat.sqlite "PRAGMA journal_mode=WAL; PRAGMA wal_checkpoint(TRUNCATE);"

      - name: Destruir base de datos antigua en Turso
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
        run: |
          # Elimina la base de datos ignorando el error si no existe la primera vez
          turso db destroy sunat --yes || true
      - name: Crear y subir nueva base de datos en Turso
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
        run: |
          # Crea la base de datos limpia importando el archivo binario fresco
          turso db create sunat --from-file output/sunat.sqlite --yes